import * as stylex from '@stylexjs/stylex';

const reveal = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(8px)' },
  to: { opacity: 1, transform: 'translateY(0)' },
});
export const s = stylex.create({
  app: {
    position: 'relative',
    width: '100%',
    height: '100%',
    color: '#f3dfbd',
    fontFamily: 'Arial, "Noto Sans JP", sans-serif',
    fontSize: 12,
    overflow: 'hidden',
    backgroundColor: '#1c2c3e',
  },
  world: { position: 'absolute', inset: 0, cursor: 'grab', ':active': { cursor: 'grabbing' } },
  vignette: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
    backgroundImage:
      'linear-gradient(180deg, rgba(16,31,44,.5) 0%, transparent 23%, transparent 62%, rgba(15,26,37,.66) 100%)',
  },
  frame: {
    position: 'absolute',
    inset: { default: 15, '@media (max-width: 600px)': 9 },
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'rgba(238,206,159,.3)',
    pointerEvents: 'none',
    zIndex: 3,
  },
  corner: {
    position: 'absolute',
    top: -5,
    left: -5,
    width: 9,
    height: 9,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#d7b889',
    transform: 'rotate(45deg)',
    backgroundColor: '#334351',
  },
  cornerBR: { top: 'auto', left: 'auto', bottom: -5, right: -5 },
  header: {
    position: 'absolute',
    top: { default: 38, '@media (max-width: 600px)': 26 },
    left: { default: 42, '@media (max-width: 600px)': 26 },
    right: { default: 42, '@media (max-width: 600px)': 26 },
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    pointerEvents: 'none',
    zIndex: 4,
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: { default: 17, '@media (max-width: 600px)': 10 },
    color: '#f3dfbd',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderStyle: 'solid',
    padding: 0,
    textAlign: 'left',
    cursor: 'pointer',
    pointerEvents: 'auto',
  },
  logo: {
    width: { default: 53, '@media (max-width: 600px)': 40 },
    height: { default: 53, '@media (max-width: 600px)': 40 },
  },
  brandTitle: {
    display: 'block',
    fontFamily: 'Georgia, "Noto Serif JP", serif',
    fontSize: { default: 29, '@media (max-width: 600px)': 20 },
    fontWeight: 500,
    letterSpacing: '.025em',
    lineHeight: 1.45,
    textShadow: '0 2px 12px #13243270',
  },
  brandSub: {
    display: 'block',
    fontFamily: 'Georgia, serif',
    fontSize: 9,
    letterSpacing: '.3em',
    marginTop: 5,
    opacity: 0.8,
  },
  motto: {
    position: 'absolute',
    left: '50%',
    transform: 'translateX(-50%)',
    whiteSpace: 'nowrap',
    fontFamily: 'Georgia, "Noto Serif JP", serif',
    fontSize: 13,
    letterSpacing: '.25em',
    opacity: 0.9,
    display: { default: 'block', '@media (max-width: 850px)': 'none' },
  },
  toolbar: {
    display: 'flex',
    gap: { default: 13, '@media (max-width: 600px)': 8 },
    pointerEvents: 'auto',
  },
  iconButton: {
    flexShrink: 0,
    display: 'grid',
    placeItems: 'center',
    width: { default: 39, '@media (max-width: 600px)': 34 },
    height: { default: 39, '@media (max-width: 600px)': 34 },
    borderRadius: '50%',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'rgba(240,215,174,.5)',
    backgroundColor: { default: 'rgba(22,40,54,.22)', ':hover': 'rgba(234,199,147,.17)' },
    color: '#f0d7ae',
    cursor: 'pointer',
    backdropFilter: 'blur(8px)',
    transition: 'background-color .2s, transform .2s',
    ':hover': { transform: 'translateY(-2px)' },
  },
  activeButton: { backgroundColor: 'rgba(234,199,147,.24)', borderColor: '#f0d7ae' },
  desktopButton: { display: { default: 'grid', '@media (max-width: 600px)': 'none' } },
  location: {
    position: 'absolute',
    bottom: { default: 58, '@media (max-width: 600px)': 220 },
    left: { default: 43, '@media (max-width: 600px)': 28 },
    pointerEvents: 'none',
    maxWidth: { default: 360, '@media (max-width: 600px)': 300 },
    zIndex: 3,
    animationName: reveal,
    animationDuration: '.65s',
  },
  smallText: { fontSize: 9, letterSpacing: '.25em', color: '#d5c5b0', fontWeight: 400 },
  placeTitle: {
    fontFamily: 'Georgia, "Noto Serif JP", serif',
    fontSize: { default: 32, '@media (max-width: 600px)': 26 },
    letterSpacing: '.025em',
    fontWeight: 400,
    margin: '8px 0 3px',
    lineHeight: 1.6,
    textShadow: '0 2px 20px #12232b',
  },
  japaneseName: {
    fontFamily: '"Noto Serif JP", serif',
    fontSize: 13,
    fontWeight: 400,
    letterSpacing: '.15em',
    color: '#d5c5b0',
    margin: '4px 0 16px',
    lineHeight: 1.6,
  },
  journalJapanese: { fontSize: 11, margin: '0 0 6px' },
  divider: {
    width: 190,
    height: 1,
    backgroundImage: 'linear-gradient(90deg,#d1b28099,transparent)',
    position: 'relative',
    marginBottom: 15,
  },
  diamond: {
    position: 'absolute',
    left: 20,
    top: -3,
    width: 6,
    height: 6,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#d1b280',
    transform: 'rotate(45deg)',
    backgroundColor: '#34404b',
  },
  placeDescription: {
    fontFamily: 'Georgia, "Noto Serif JP", serif',
    fontSize: { default: 11, '@media (max-width: 600px)': 10 },
    letterSpacing: '.1em',
    lineHeight: 2,
    color: '#ded1bd',
    margin: 0,
  },
  controls: {
    position: 'absolute',
    bottom: 34,
    left: '50%',
    transform: 'translateX(-50%)',
    display: { default: 'flex', '@media (max-width: 900px)': 'none' },
    alignItems: 'center',
    gap: 16,
    padding: '10px 18px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'rgba(220,196,158,.2)',
    borderRadius: 4,
    backgroundColor: 'rgba(19,33,42,.5)',
    backdropFilter: 'blur(12px)',
    whiteSpace: 'nowrap',
    color: '#d3c7b2',
    fontSize: 10,
    letterSpacing: '.05em',
    zIndex: 3,
  },
  controlPart: { display: 'flex', alignItems: 'center', gap: 7 },
  key: {
    display: 'inline-grid',
    placeItems: 'center',
    minWidth: 18,
    height: 20,
    padding: '0 3px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'rgba(230,206,167,.4)',
    borderRadius: 2,
    fontFamily: 'Georgia, serif',
    color: '#ebd7b6',
    fontSize: 11,
  },
  controlDivider: { width: 1, height: 14, backgroundColor: '#d8c19d33' },
  interact: {
    position: 'absolute',
    bottom: { default: 98, '@media (max-width: 600px)': 155 },
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    alignItems: 'center',
    gap: 13,
    padding: '12px 18px',
    backgroundColor: { default: 'rgba(25,42,49,.82)', ':hover': 'rgba(49,66,68,.95)' },
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#d0ba8f88',
    borderRadius: 5,
    backdropFilter: 'blur(12px)',
    color: '#f2dfba',
    textAlign: 'left',
    cursor: 'pointer',
    boxShadow: '0 5px 24px #07151e25',
    zIndex: 4,
    whiteSpace: 'nowrap',
  },
  interactSub: {
    display: 'block',
    fontSize: 8,
    letterSpacing: '.17em',
    color: '#c1b59f',
    marginBottom: 4,
  },
  interactTitle: {
    fontFamily: 'Georgia, "Noto Serif JP", serif',
    fontSize: 12,
    letterSpacing: '.1em',
  },
  mapArea: {
    position: 'absolute',
    bottom: { default: 36, '@media (max-width: 600px)': 33 },
    right: { default: 35, '@media (max-width: 600px)': 24 },
    zIndex: 4,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
  },
  mapButton: {
    width: { default: 158, '@media (max-width: 600px)': 100 },
    height: { default: 158, '@media (max-width: 600px)': 100 },
    padding: 0,
    borderWidth: 0,
    borderStyle: 'solid',
    borderRadius: '50%',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    transition: 'transform .2s',
    ':hover': { transform: 'scale(1.04)' },
  },
  mapCaption: {
    fontSize: 9,
    letterSpacing: '.16em',
    color: '#ddd0ba',
    display: 'flex',
    gap: 10,
    alignItems: 'center',
  },
  toast: {
    position: 'absolute',
    top: 125,
    left: '50%',
    transform: 'translateX(-50%)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#d7bf8e55',
    borderRadius: 4,
    backgroundColor: '#233b46eb',
    padding: '13px 22px',
    color: '#f2dfba',
    maxWidth: 'calc(100% - 50px)',
    textAlign: 'center',
    fontSize: 12,
    zIndex: 10,
    boxShadow: '0 8px 30px #10232a30',
  },
  loading: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 20,
    backgroundColor: '#233b47',
    zIndex: 20,
    color: '#eddbba',
  },
  loadingTitle: {
    fontFamily: 'Georgia, "Noto Serif JP", serif',
    fontSize: 30,
    fontWeight: 400,
    letterSpacing: '.3em',
    margin: 0,
  },
  loadingCopy: {
    fontSize: 12,
    letterSpacing: '.025em',
    lineHeight: 2,
    textAlign: 'center',
    padding: '0 25px',
    margin: 0,
  },
  dialog: {
    width: 'min(510px, calc(100% - 40px))',
    maxHeight: 'calc(100dvh - 60px)',
    color: '#eedcc0',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#b39b7466',
    borderRadius: 9,
    padding: { default: 35, '@media (max-width: 600px)': 25 },
    backgroundColor: '#243943f5',
    boxShadow: '0 25px 100px #081c3066',
    fontFamily: 'Arial, "Noto Sans JP", sans-serif',
    '::backdrop': { backgroundColor: '#0d202c80', backdropFilter: 'blur(5px)' },
  },
  dialogTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 15,
    marginBottom: 26,
  },
  dialogTitle: {
    fontFamily: 'Georgia, "Noto Serif JP", serif',
    fontSize: 27,
    letterSpacing: '.025em',
    fontWeight: 400,
    margin: '7px 0 0',
  },
  story: {
    fontFamily: 'Georgia, "Noto Serif JP", serif',
    fontSize: 14,
    lineHeight: 2.5,
    letterSpacing: '.05em',
    margin: '0 0 25px',
    color: '#e2d5bf',
  },
  action: {
    width: '100%',
    padding: '13px 20px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#d4b58177',
    borderRadius: 4,
    backgroundColor: { default: '#e1c397', ':hover': '#f1d6ac' },
    color: '#293d43',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 500,
    letterSpacing: '.12em',
  },
  helpRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    fontSize: 12,
    padding: '13px 0',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: '#ddcba31c',
    lineHeight: 1.8,
  },
  helpKeys: { display: 'flex', alignItems: 'center', gap: 4, color: '#b6c5c9', fontSize: 11 },
  helpFooter: { color: '#b9c6c6', fontSize: 11, lineHeight: 2.2, marginTop: 22 },
  journalRow: {
    display: 'flex',
    gap: 17,
    alignItems: 'center',
    padding: '17px 0',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: '#ddcba31c',
  },
  stamp: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#d2b17d44',
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
    color: '#91a0a0',
    fontFamily: 'Georgia, "Noto Serif JP", serif',
    fontSize: 20,
    flexShrink: 0,
  },
  stamped: {
    borderColor: '#e1a481',
    color: '#e1a481',
    backgroundColor: '#a5664420',
    transform: 'rotate(-9deg)',
  },
  journalName: {
    fontFamily: 'Georgia, "Noto Serif JP", serif',
    fontSize: 16,
    fontWeight: 400,
    margin: '0 0 5px',
  },
  journalDesc: { fontSize: 10, color: '#bdc7c7', margin: 0, lineHeight: 1.8 },
  journalCheck: { marginLeft: 'auto', flexShrink: 0, color: '#dfc69e' },
  touch: {
    position: 'absolute',
    bottom: 37,
    left: 30,
    display: {
      default: 'none',
      '@media (pointer: coarse)': 'grid',
      '@media (max-width: 600px)': 'grid',
    },
    gridTemplateColumns: 'repeat(3, 31px)',
    gridTemplateRows: 'repeat(3, 28px)',
    gap: 3,
    zIndex: 5,
  },
  touchButton: {
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#ecd5a744',
    backgroundColor: '#213a4999',
    color: '#efdbb7',
    borderRadius: 4,
    display: 'grid',
    placeItems: 'center',
    touchAction: 'none',
    userSelect: 'none',
  },
  touchUp: { gridColumn: 2, gridRow: 1 },
  touchLeft: { gridColumn: 1, gridRow: 2 },
  touchRight: { gridColumn: 3, gridRow: 2 },
  touchDown: { gridColumn: 2, gridRow: 3 },
  photoReturn: {
    position: 'absolute',
    bottom: 30,
    left: '50%',
    transform: 'translateX(-50%)',
    color: '#f1dabb',
    backgroundColor: '#213746b3',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#d0ba8f66',
    padding: '11px 20px',
    borderRadius: 4,
    cursor: 'pointer',
    zIndex: 5,
  },
});
